#!/usr/bin/env python3
"""
Convert SPIR-V binary to C++ header file with embedded bytecode.

Usage:
    python3 spv_to_cpp.py bilateral_filter.spv bilateral_filter_spv.h
"""

import sys
import os

def spv_to_cpp(spv_file, output_file):
    """Convert SPIR-V binary to C++ header with uint32_t array."""
    
    # Read SPIR-V binary
    with open(spv_file, 'rb') as f:
        data = f.read()
    
    # Verify SPIR-V magic number
    if len(data) < 4:
        print(f"Error: {spv_file} is too small to be a valid SPIR-V file")
        return False
    
    magic = int.from_bytes(data[0:4], byteorder='little')
    if magic != 0x07230203:
        print(f"Warning: {spv_file} does not have SPIR-V magic number (0x07230203)")
        print(f"Found: 0x{magic:08x}")
    
    # Convert to uint32_t array
    words = []
    for i in range(0, len(data), 4):
        if i + 4 <= len(data):
            word = int.from_bytes(data[i:i+4], byteorder='little')
            words.append(word)
        else:
            # Pad with zeros if not aligned
            remaining = data[i:]
            padded = remaining + b'\x00' * (4 - len(remaining))
            word = int.from_bytes(padded, byteorder='little')
            words.append(word)
    
    # Generate C++ header
    base_name = os.path.splitext(os.path.basename(spv_file))[0].upper()
    
    with open(output_file, 'w') as f:
        f.write('// Auto-generated SPIR-V bytecode\n')
        f.write(f'// Source: {os.path.basename(spv_file)}\n')
        f.write('// DO NOT EDIT - This file is generated by spv_to_cpp.py\n\n')
        f.write('#ifndef FILMTRACKER_SHADER_SPV_H\n')
        f.write('#define FILMTRACKER_SHADER_SPV_H\n\n')
        f.write('#include <cstdint>\n\n')
        f.write(f'// SPIR-V bytecode for {base_name}\n')
        f.write(f'static const uint32_t {base_name}_SPV[] = {{\n')
        
        # Write words in rows of 8
        for i, word in enumerate(words):
            if i % 8 == 0:
                f.write('    ')
            f.write(f'0x{word:08x}')
            if i < len(words) - 1:
                f.write(',')
            if i % 8 == 7 or i == len(words) - 1:
                f.write('\n')
            else:
                f.write(' ')
        
        f.write('};\n\n')
        f.write(f'static const size_t {base_name}_SPV_SIZE = {len(words)};\n\n')
        f.write('#endif // FILMTRACKER_SHADER_SPV_H\n')
    
    print(f"Successfully converted {spv_file} to {output_file}")
    print(f"SPIR-V size: {len(data)} bytes ({len(words)} words)")
    return True

def main():
    if len(sys.argv) != 3:
        print(f'Usage: {sys.argv[0]} <input.spv> <output.h>')
        print()
        print('Example:')
        print(f'  {sys.argv[0]} bilateral_filter.spv bilateral_filter_spv.h')
        sys.exit(1)
    
    spv_file = sys.argv[1]
    output_file = sys.argv[2]
    
    if not os.path.exists(spv_file):
        print(f"Error: Input file '{spv_file}' not found")
        sys.exit(1)
    
    if not spv_to_cpp(spv_file, output_file):
        sys.exit(1)

if __name__ == '__main__':
    main()
